import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {NavigationBar} from "@/components/custom/navigation/navigation-bar";
import {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {AsideBar} from "@/components/custom/aside/aside-bar";
import {ThemeProvider} from "@/components/theme/theme-provider";
import React from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute={"class"}
          defaultTheme={"system"}
          enableSystem
          storageKey="theme"
        >
          <SidebarProvider className="flex flex-row">
            <AsideBar />
            <section className="flex flex-col w-full">
              <NavigationBar asideTrigger={<SidebarTrigger />} />
              {children}
            </section>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>

  );
}
